language: node_js
node_js: "8"
cache:
  directories:
    - node_modules
    - client/node_modules
branches:
  only:
    - master
services:
  - mongodb
env:
  - MONGODB_TEST_URI="mongodb://localhost/nomz_test"