const scraper = require('../scraper/scraper');

describe('Test Menu Overview Scraper', () => {
  it('check menu parsing against a known menu', () => {
    const trueItems = [
      {
        recipeId: '089003',
        recipeSize: '2',
        diningHall: 'Covel',
        diningSection: 'Euro Kitchen',
        menuPeriod: 'Breakfast',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '111187',
        recipeSize: '1',
        diningHall: 'Covel',
        diningSection: 'Euro Kitchen',
        menuPeriod: 'Breakfast',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '061005',
        recipeSize: '1',
        diningHall: 'Covel',
        diningSection: 'Euro Kitchen',
        menuPeriod: 'Breakfast',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '061102',
        recipeSize: '2',
        diningHall: 'Covel',
        diningSection: 'Euro Kitchen',
        menuPeriod: 'Breakfast',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '217001',
        recipeSize: '2',
        diningHall: 'Covel',
        diningSection: 'Grill',
        menuPeriod: 'Breakfast',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '089011',
        recipeSize: '2',
        diningHall: 'De Neve',
        diningSection: 'The Kitchen',
        menuPeriod: 'Breakfast',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '970747',
        recipeSize: '2',
        diningHall: 'De Neve',
        diningSection: 'The Kitchen',
        menuPeriod: 'Breakfast',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '061102',
        recipeSize: '3',
        diningHall: 'De Neve',
        diningSection: 'The Kitchen',
        menuPeriod: 'Breakfast',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '302004',
        recipeSize: '6',
        diningHall: 'Covel',
        diningSection: 'Exhibition Kitchen',
        menuPeriod: 'Lunch',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '302003',
        recipeSize: '6',
        diningHall: 'Covel',
        diningSection: 'Exhibition Kitchen',
        menuPeriod: 'Lunch',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '075000',
        recipeSize: '1',
        diningHall: 'Covel',
        diningSection: 'Euro Kitchen',
        menuPeriod: 'Lunch',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '140395',
        recipeSize: '1!10',
        diningHall: 'Covel',
        diningSection: 'Pizza Oven',
        menuPeriod: 'Lunch',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '111219',
        recipeSize: '1',
        diningHall: 'De Neve',
        diningSection: 'Flex Bar',
        menuPeriod: 'Lunch',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '977625',
        recipeSize: '3',
        diningHall: 'De Neve',
        diningSection: 'Flex Bar',
        menuPeriod: 'Lunch',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '140062',
        recipeSize: '6',
        diningHall: 'De Neve',
        diningSection: 'The Front Burner',
        menuPeriod: 'Lunch',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '140060',
        recipeSize: '6',
        diningHall: 'De Neve',
        diningSection: 'The Front Burner',
        menuPeriod: 'Lunch',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '971201',
        recipeSize: '1',
        diningHall: 'De Neve',
        diningSection: 'The Kitchen',
        menuPeriod: 'Lunch',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '175012',
        recipeSize: '2',
        diningHall: 'De Neve',
        diningSection: 'The Kitchen',
        menuPeriod: 'Lunch',
        menuDate: 'November 13, 2019',
      },
      {
        recipeId: '141026',
        recipeSize: '1!10',
        diningHall: 'De Neve',
        diningSection: 'The Pizzeria',
        menuPeriod: 'Lunch',
        menuDate: 'November 13, 2019',
      },
    ];
    return scraper.getMenu('2019-11-13').then((items) => expect(items).toEqual(trueItems));
  });
});
